# Generated by Django 2.1.5 on 2020-03-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='question')),
                ('choice1', models.TextField(verbose_name='choice1')),
                ('choice2', models.TextField(verbose_name='choice2')),
                ('choice3', models.TextField(verbose_name='choice3')),
                ('choice4', models.TextField(verbose_name='choice4')),
                ('answer', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('created_date', models.DateField(auto_now=True)),
                ('url', models.URLField(null=True, verbose_name='url')),
            ],
        ),
    ]
